---
title: "Assignment3"
author: "Huiyi Huang"
date: "9/30/2019"
output: pdf_document
---
#1 redo 13-26



```{r}
setwd("C:/Users/student/Documents/Fall2019/")
getwd

#install.packages("dplyr")

library(dplyr)
Titanic<-read.csv(file= 'titanic.csv')
```

#1 redo 13-26

```{r}
Titanic %>%
  select(Age,Sex)%>%
  #13
  filter(Sex=="female",Age)%>%
  summarise(mean_female_age = mean(Age))


```

```{r}
#14 Calculate the median fare of the passengers in Class 1
Titanic %>%
  select(Fare,Pclass)%>%
  filter(Pclass == 1) %>%
  summarise(median_fare_class1 = median(Fare))


median(Titanic$Fare[Titanic$Pclass=='1'])

  
```
```{r}
#15. Calculate the median fare of the female passengers that are not in Class 1
Titanic %>%
  select(Fare,Pclass,Sex)%>%
  filter(Sex=='female', Pclass!= 1)%>%
  summarise(median(Fare))


```

```{r}
#16. Calculate the median age of survived passengers who are female and Class 1 or Class 2,

Titanic %>%
  select(Age,Survived,Sex,Pclass)%>%
  filter(Survived==1, Sex=="female",Pclass !=3,Age != 'NA' ) %>%
  summarise(median(Age))
```


```{r}
#17. Calculate the mean fare of female teenagers survived passengers
Titanic %>%
  select(Age,Survived,Sex,Fare)%>%
  filter(Survived==1, Sex=="female",Age < 18)  %>%
  summarise(mean(Fare))

```

```{r}
#18. Calculate the mean fare of female teenagers survived passengers for each class
Titanic %>%
  group_by(Pclass) %>% 
  summarise(m=mean(Fare))
  
  
```

```{r}
#19. Calculate the ratio of Survived and not Survived for passengers who are who pays more than the
#average fare
Titanic %>%
  group_by(Survived)%>%
  summarize(mean(Fare))
  48.39541/22.11789

```
```{r}
#20. Add column that standardizes the fare (subtract the mean and divide by standard deviation) and name
#it sfare
T =Titanic %>%
  mutate(S_fare= (Fare-mean(Fare))/sd(Fare))

```
```{r}
#21. Add categorical variable named cfare that takes value cheap for passengers paying less the average
#fare and takes value expensive for passengers paying more than the average fare.
T =Titanic %>%
  mutate(cfare= ifelse(Fare>mean(Fare),'expensive','cheap'))




```
```{r}
#22. Add categorical variable named cage that takes value 0 for age 0-10, 1 for age 10-20, 2 for age 20-30,
#and so on
T =Titanic %>%
  mutate(cage = case_when(Age<10~'0',
                          (Age>=10)&(Age<20)~'1',
                          (Age>=20)&(Age<30)~'2',
                          (Age>=30)&(Age<40)~'3',
                          (Age>=40)&(Age<50)~'4',
                          (Age>=50)&(Age<60)~'5',
                          (Age>=60)&(Age<70)~'6',
                          (Age>=70)&(Age<80)~'7',
                          (Age>=80)~'8'))
  

```
```{r}
#23. Show the frequency of Ports of Embarkation. It appears that there are two missing values in the
#Embarked variable. Assign the most frequent port to the missing ports. Hint: Use the levels
#function to modify the categories of categorical variables.
Titanic %>%
  count(Embarked)%>%
  mutate(Embarked=replace(Embarked,Embarked=='','S'))

```

#2 assignment2 question 4 
```{r}
#install.packages('readxl') # install the library
library(readxl) # load the library
```


```{r}
#2. Using Dplyr and in Assignment 2, redo 4 using sample_n function, redo 5 using glimpse, redo 11, 12
#and 13. For 11, 12 and 13, you may want to use the combo group_by and summarise
read_excel("C:/Users/student/Documents/Fall2019/c2015.xlsx")
c2015=read_excel("C:/Users/student/Documents/Fall2019/c2015.xlsx")

set.seed(2019)
y<- sample_n(c2015,1000)

```
```{r}
#5. Use summary function to have a quick look at the data. You will notice there is one variable is actually
#5a constant. Remove that variable from the data.

glimpse(y)
```
```{r}
#11. Compare the average speed of those who had "No Apprent Injury" and the rest. What do you
#observe?
#12. Use the SEAT_POS variable to filter the data so that there is only drivers in the dataset. Compare the
#average speed of man drivers and woman drivers. Comment on the results.
#13. Compare the average speed of drivers who drink and those who do not. Comment on the results.
#Hint: This calculation can be done manually or by using the aggregate function or by function in
#base R. For example:
library(stringr)
#11
y%>%
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  group_by(INJ_SEV)%>%
  summarise(mean(TRAV_SP1))
#Obviously, no injury type of drivers who have slower speed comparing to other drivers who have injuries.

```
```{r}
#12
y%>%
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  filter(SEAT_POS=="Front Seat, Left Side")%>%
  group_by(SEX) %>%
  summarise(mean(TRAV_SP1))
#Male drivers tend to drive faster than female drivers

```
```{r}
#13
y%>%
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  group_by(DRINKING)%>%
  summarise(mean(TRAV_SP1))
#Drinking alcohol drivers drive faster than not drinking drivers

```
```{r}
#3. Calculate the travel speed (TRAV_SP variable) by day. Compare the travel speed of the first 5 days and
#the last 5 days of months.
y%>%  
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  filter(DAY==1:5)%>%
  group_by(DAY)%>%
  summarise(mean = mean(TRAV_SP1))%>%
  summarise(fist_5_day_mean=mean(mean))
  

```
```{r}
#continued question 3
y%>%  
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  filter(DAY==27:31)%>%
  group_by(DAY)%>%
  summarise(mean2 = mean(TRAV_SP1)) %>%
  summarise(last_5_day_mean=mean(mean2))
# From calculated the mean of first 5 days and last 5 days mean speed, here comes conclusion: people whill travel faster during last 5 days.
```
```{r}
#4. Calculate the travel speed (TRAV_SP variable) by day of the week. Compare the travel speed of the
#weekdays and weekends.
y%>%  
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  group_by(DAY_WEEK=="Saturday" | DAY_WEEK=="Sunday")%>%
  summarise(mean(TRAV_SP1))
#The comparasion calculated the mean of speed when day of week is weekend or not. The conclusion is that : people travel faster on weekend than on weekdays.

```
```{r}
#5. Find the top 5 states with greatest travel speed.
y%>%  
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  group_by(STATE)%>%
  summarise(mean=mean(TRAV_SP1))%>%
  top_n(5,mean)


```

```{r}
#6. Rank the travel speed by MONTH

y%>%  
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  group_by(MONTH)%>%
  summarise(mean=mean(TRAV_SP1))%>%
  arrange(desc(mean))

```
```{r}
#7. Find the average speed of teenagers in December.
y%>%  
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  filter(AGE<18 & MONTH=="December")%>%
  summarise(mean(TRAV_SP1))

```
```{r}
#8. Find the month that female drivers drive fastest on average.
y%>%  
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  filter(SEX=="Female")%>%
  group_by(MONTH)%>%
  summarise(mean=mean(TRAV_SP1))%>%
  top_n(1,mean)

```
```{r}
#9. Find the month that male driver drive slowest on average.
y%>%  
  mutate(TRAV_SP1=str_replace(TRAV_SP," MPH","")) %>%
  mutate(TRAV_SP1 = as.numeric(TRAV_SP1))%>%
  mutate(TRAV_SP1 = replace(TRAV_SP1,is.na(TRAV_SP1),mean(TRAV_SP1,na.rm=TRUE))) %>%
  filter(SEX=="Male")%>%
  group_by(MONTH)%>%
  summarise(mean=mean(TRAV_SP1))%>%
  arrange(mean)
#It's Febrary.
```
```{r}
#10. Create a new column containing information about the season of the accidents. Compare the percentage of Fatal Injury by seasons.
y1 = y%>%  
  mutate(SEASON=case_when(
    MONTH == "March"|MONTH =="April"|MONTH =="May"~"Spring",
    MONTH == "June"|MONTH =="July"|MONTH =="August"~ "Summer",
    MONTH == "September"|MONTH =="October"|MONTH =="November"~"Autumn",
    MONTH == "December"|MONTH =="January"|MONTH =="February"~"Winter"))

  
  
```
```{r}
#continue question10
y1 %>% 
  group_by(SEASON) %>% summarize(prop=prop.table(table(INJ_SEV))[1])


```
```{r}
#11. Compare the percentage of fatal injuries for different type of deformations (DEFORMED variable)
y%>%  

  

  group_by(INJ_SEV,DEFORMED) %>% 
  summarise(n =n()) %>% 
  mutate(prop=n/sum(n))
```

